name: build

on: 
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  nes:
    if: false
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Restore vendor cache
        uses: actions/cache@v3
        with:
          path: ./vendor/
          key: cc65
      -
        name: Prepare project (Cmake)
        run: cmake . -DCMAKE_MAKE_PROGRAM=make
      -
        name: Build project (Makefile)
        run: make
      -
        name: Upload roms artifacts
        uses: actions/upload-artifact@v3
        with:
          name: roms
          path: bin/*.nes
          if-no-files-found: error
          retention-days: 1

  html5:
      runs-on: ubuntu-latest
      steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Prepare project (Cmake)
        run: cmake . -DCMAKE_MAKE_PROGRAM=make -DCMAKE_C_FLAGS="-DMAX_PLAYERS=1"
      -
        name: Build project (Makefile)
        run: make
      -
        name: Build page (Makefile)
        run: >-
          mkdir -p html &&
          sh -c 'awk "{gsub(/{{game}}/, \"Kokobatoru 2\");} /{{rom}}/ {cmd=\"base64 bin/kokobatoru.nes\"; cmd | getline var; close(cmd); gsub(/{{rom}}/, var);} 1" res/index.html' > html/kokobatoru.html &&
          sh -c 'awk "{gsub(/{{game}}/, \"Coco Battle Royale II\");} /{{rom}}/ {cmd=\"base64 bin/cocobattleroyale.nes\"; cmd | getline var; close(cmd); gsub(/{{rom}}/, var);} 1" res/index.html' > html/cocobattleroyale.html
      -
        name: Setup Pages
        uses: actions/configure-pages@v3
      -
        name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'html'
      -
        id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
